### ISSUE TITLE
Pass TES endpoints to WES request

### ISSUE THREAD

**Issue by uniqueg** [ga4gh/workflow-execution-service-schemas#170]
For WES implementations that support TES (e.g. [cwl-WES](https://github.com/elixir-cloud-aai/cwl-WES)), there is currently not an mechanism to provide a list of acceptable TES endpoints, requiring TES endpoints themselves or a mechanism to obtain them (e.g., from a GA4GH Service Registry) to be pre-configured in a given WES instance.

To enable effective task-level compute federation, it would be beneficial to add a way to pass either:
- an array of TES instances that a WES could use
- an array of Service Registries that WES could query to obtain a list of available TES instances

The mechanism could then be used to (1) allow a WES client to designate TES backends that the WES can use and (2) provide inputs to a task distribution middleware (e.g., [TEStribute](https://github.com/elixir-cloud-aai/TEStribute)) integrated into a WES instance to "smartly" determine the best TES for a given task, e.g., the TES instance that is closest to the bulk of the data, has the lowest load.

The property should be optional in general, but any given WES implementation may choose to require it. Here's a quick-and-dirty draft for a corresponding schema:

```yaml
TesBackends:
  type: object
  tes_urls:
    type: array
    items:
      type: string
  service_registry_urls:
    type: array
    items:
        type: str
  description: TES backends to be used to execute the workflow run.
```

Something like the following could then be added to the `RunRequest` schema:

```yaml
tes_backends:
  $ref: '#/definitions/TesBackends'
  description: TES backends to be used to execute the workflow run.
```
