### ISSUE TITLE
Schema proposal discussion

### ISSUE THREAD

**Issue by ntijanic** [ga4gh/workflow-execution-service-schemas#2]
Regarding the design sketch here: https://github.com/ga4gh/workflow-execution-schemas/blob/proposal/Flow.md

Some possible flavour changes:

1) Unify GET and POST models. When POSTing a new job (i.e. WorkflowInstance or TaskInstance), we can use the same model (with a subset of fields) that is returned when querying for status. The example submission POST data would look like this:

``` json
{
  "tool": "http://example.com/tools/bwa/version/1.0/descriptor",
  "input": {
    "stringparameter": "value",
    "fileparameter": {
      "class": "File",
      "location": "http://storage.example.com/bucket/file1.fq"
    }
  }
}
```

2) POST to collection endpoint, not to `/submit`. So, we'd have `POST http://example.com/workflows` and `GET http://example.com/workflows/:id`.

3) A more suitable endpoint name may be `/jobs`, but is usually irrelevant (implementation detail?).

4) When representing files, replace `class` key with `$type` to avoid possible conflicts with record values.

5) Split the `queued` state into `pending` and `ready` to differentiate between jobs that are waiting for dependency jobs and jobs that may be waiting for e.g. compute resources.

6) We may want to show inputs and outputs of subjobs. For this it may make sense to introduce `rootId` and `parentId` properties to each job (including top-level jobs), then let people query with e.g. `example.com/jobs?parentId=:id` to traverse the tree rather than include it in the top-level job.

**Comment by ntijanic** [comment]
A few examples on what the API could look like. These are for a mock "bwa_parallel" workflow which splits the input fastq file, runs BWA for each chunk, then merges the bam files in third step.

To submit the job:
```yaml
# POST <endpoint>/

descriptor: http://example.com/workflows/bwa_parallel/version/1.0/descriptor
input:
  string_parameter: value
  file_parameter:
    $type: File
    location: http://storage.example.com/bucket/file1.fq
```

You'd be redirected to `<endpoint>/abc1234`, assuming the system assigned `abc1234` identifier for the job:
```yaml
# GET <endpoint>/abc1234

id: abc1234
status: complete
message: "Done"
overview:
  complete: 4
  failed: 0
  running: 0
  pending: 0
descriptor: http://example.com/workflows/bwa_parallel/version/1.0/descriptor
input:
  string_parameter: value
  file_parameter:
    $type: File
    location: http://storage.example.com/bucket/file1.fq
output:
  file_output:
    $type: File
    location: http://storage.example.com/bucket/file1.bam
```

To see all tasks for the workflow:
```yaml
# GET <endpoint>/abc1234/tasks

- id: root.step1
  status: complete
  message: "Done"
- id: root.step2.1
  status: complete
  message: "Done"
- id: root.step2.2
  status: complete
- id: root.step3
  status: complete
  message: "Done"
```

To get detailed data for individual task:
```yaml
# GET <endpoint>/abc1234/tasks/root.step1

id: root.step1
status: complete
message: "Done"
descriptor: null  # Sometimes applicable, possibly a data URL
input:
  string_parameter: value
  file_parameter:
    $type: File
    location: http://storage.example.com/bucket/file1.fq
output:
  chunks:
    - $type: File
      location: http://storage.example.com/temp/file1.1.fq
    - $type: File
      location: http://storage.example.com/temp/file1.2.fq
runs:
  - commandLine: "./split file1.fq"
    startTime: "2016-05-16T12:32:43Z"
    endTime: "2016-05-16T13:32:43Z"
    exitCode: 0
    imageChecksum: "md5$checksum"
    stderr: ""
    stdout: ""
```
