### ISSUE TITLE
system_state_count description missing

### ISSUE THREAD

**Issue by uniqueg** [ga4gh/workflow-execution-service-schemas#221]
It seems that the `description` for `system_state_counts` in the `ServiceInfo` model got inadvertently lost between [1.0.0](https://github.com/ga4gh/workflow-execution-service-schemas/blob/c5406f1d3740e21b93d3ac71a4c8d7b874011519/openapi/workflow_execution_service.swagger.yaml) and [1.0.1](https://github.com/ga4gh/workflow-execution-service-schemas/blob/13f56821fb50e4b01a269354421c96c20785e909/openapi/workflow_execution_service.openapi.yaml) when migrating from Swagger/OpenAPI v2 to OpenAPI v3.

Since [version 1.0.1](https://github.com/ga4gh/workflow-execution-service-schemas/blob/13f56821fb50e4b01a269354421c96c20785e909/openapi/workflow_execution_service.openapi.yaml#L457-L460):

```yaml
components:
  schemas:
    ServiceInfo:
      title: ServiceInfo
      allOf:
        - $ref: 'https://raw.githubusercontent.com/ga4gh-discovery/ga4gh-service-info/v1.0.0/service-info.yaml#/components/schemas/Service'
        - type: object
          properties:
            ...
            system_state_counts:
              type: object
              additionalProperties:
                type: integer
                format: int64
            auth_instructions_url:
              ...
```

> Note that the description is still available in the [Swagger/OpenAPI 2 version](https://github.com/ga4gh/workflow-execution-service-schemas/blob/13f56821fb50e4b01a269354421c96c20785e909/openapi/workflow_execution_service.swagger.yaml) of the specs that was dropped in the [latest version v1.1.0](https://github.com/ga4gh/workflow-execution-service-schemas/releases/tag/1.1.0). 

[Version 1.0.0](https://github.com/ga4gh/workflow-execution-service-schemas/blob/c5406f1d3740e21b93d3ac71a4c8d7b874011519/openapi/workflow_execution_service.swagger.yaml#L412-L419):

```yaml
definitions:
  ...
  ServiceInfo:
    type: object
    properties:
      ...
      system_state_counts:
        type: object
        additionalProperties:
          type: integer
          format: int64
        description: >-
          The system statistics, key is the statistic, value is the count of runs in that state.
          See the State enum for the possible keys.
      auth_instructions_url:
        ...
```
