### ISSUE TITLE
Use JSON schemas required notation everywhere

### ISSUE THREAD

**Issue by david4096** [ga4gh/workflow-execution-service-schemas#82]
Another artifact of converting from protobuf IDL was that we did not use the "required" notation in the schema description. In many places it is a comment, making the item optional to automated clients.

Some parameter's required properties use the correct notation: https://github.com/ga4gh/workflow-execution-service-schemas/blob/develop/openapi/workflow_execution_service.swagger.yaml#L89 , while some do not https://github.com/ga4gh/workflow-execution-service-schemas/blame/develop/openapi/workflow_execution_service.swagger.yaml#L455

To close this, set the items that are commented or titled "required" to `required: true`.

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md

**Comment by jaeddy** [comment]
So, this is a bit odd, but I'm pretty sure that the `required: true/false` convention only applies to *parameters*. In contrast, for `properties` (or other object definitions), `required` should be an array — i.e.:

**property:**
```yaml
parameters:
- name: id
  in: path
  description: ID of pet to use
  required: true
  type: array
  items:
    type: string
  collectionFormat: csv
```

**schema:**
```yaml
type: object
required:
- name
properties:
  name:
    type: string
  address:
    $ref: '#/definitions/Address'
  age:
    type: integer
    format: int32
    minimum: 0
```
