### ISSUE TITLE
Hosted swagger is out of date?

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/workflow-execution-service-schemas#87]
I think this is out of date:

https://ga4gh.github.io/workflow-execution-service-schemas/#/WorkflowExecutionService/GetServiceInfo

Can this be setup to be updated via travis CI?

**Comment by jaeddy** [comment]
Seems like that should be do-able. I can look into it.

**Comment by jaeddy** [comment]
You could add these lines to `.travis.yml` (I think):

```yaml
sudo: required

services:
  - docker

after_success:
  - docker pull swaggerapi/swagger-ui
  - docker run -p 80:8080 -e SWAGGER_JSON=/workflow_execution_service.swagger.json -v /openapi:/ swaggerapi/swagger-ui
deploy:
  - provider: pypi
    ...
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      all_branches: true
```
